#!/usr/bin/env bash
while true
do
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
IPPUB=`curl -s http://api.ipify.org`
IPPRV=`ip a | egrep '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]+' -o | sed 's/^/ * /'`
HOSTNAME=`hostname -f`
echo -e "$HOSTNAME online.\nPublic IP address: $IPPUB\nLocal IP addresses:\n$IPPRV\n" | mailx -v -s "$HOSTNAME restarted" -S smtp="mx.lists.illallangi.enterprises:25" illallangi-infrastructure@lists.illallangi.enterprises
exit 0
else
sleep 5
fi
done

